democraciakit/contenidos/urls.py
from django.urls import path, include
from . import views
from .views import *

app_name = "contenidos"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("mikit/", views.MikitView.as_view(), name="mikit"),
    path("derechos/", views.DerechosView.as_view(), name="derechos"),
    path("rueda/", views.RuedaView.as_view(), name="rueda"),
    path("etapa1/", views.Etapa1View.as_view(), name="etapa1"),
    path("quees/", views.QueesView.as_view(), name="quees"),
    path("inicio/", views.InicioView.as_view(), name="inicio"),
    path(
        "etapa1-conceptos/",
        views.Etapa1ConceptosView.as_view(),
        name="etapa1-conceptos",
    ),
    path(
        "etapa1-definicion/",
        views.Definicion1CreateView.as_view(),
        name="etapa1-definicion",
    ),
    path(
        "etapa1-estrategia/",
        views.Etapa1EstrategiaView.as_view(),
        name="etapa1-estrategia",
    ),
    path("etapa1-sesgo/", views.Etapa1SesgoView.as_view(), name="etapa1-sesgo"),
    path("etapa2/", views.Etapa2View.as_view(), name="etapa2"),
    path("etapa2-matriz/", views.Etapa2MatrizView.as_view(), name="etapa2-matriz"),
    path(
        "etapa2-mapaafinidad/",
        views.MapaAfinidad2CreateView.as_view(),
        name="etapa2-mapaafinidad",
    ),
    path(
        "etapa2-inclusivo/",
        views.Inclusivo2CreateView.as_view(),
        name="etapa2-inclusivo",
    ),
    path(
        "etapa2-identificacion/",
        views.IdentificacionCreateView.as_view(),
        name="etapa2-identificacion",
    ),
    path("etapa3/", views.Etapa3View.as_view(), name="etapa3"),
    path("etapa3-3x3x3/", views.Etapa33x3x3View.as_view(), name="etapa3-3x3x3"),
    path(
        "etapa3-sombreros/",
        views.Etapa3SombrerosView.as_view(),
        name="etapa3-sombreros",
    ),
    path(
        "etapa3-reflexionar/",
        views.Etapa3ReflexionarView.as_view(),
        name="etapa3-reflexionar",
    ),
    path("etapa3-smart/", views.Etapa3SmartView.as_view(), name="etapa3-smart"),
    path("etapa4/", views.Etapa4View.as_view(), name="etapa4"),
    path(
        "etapa4-proyeccion/",
        views.Etapa4ProyeccionView.as_view(),
        name="etapa4-proyeccion",
    ),
    path(
        "etapa4-mapaactores/",
        views.Etapa4MapaactoresView.as_view(),
        name="etapa4-mapaactores",
    ),
    path("etapa4-eventos/", views.Etapa4EventosView.as_view(), name="etapa4-eventos"),
    path(
        "etapa4-oportunidades/",
        views.Etapa4OportunidadesView.as_view(),
        name="etapa4-oportunidades",
    ),
    path(
        "etapa4-plandetrabajo/",
        views.Etapa4PlandetrabajoView.as_view(),
        name="etapa4-plandetrabajo",
    ),
    path("etapa5/", views.Etapa5View.as_view(), name="etapa5"),
    path(
        "etapa5-keepfixtry/",
        views.Etapa5KeepfixtryView.as_view(),
        name="etapa5-keepfixtry",
    ),
    path(
        "etapa5-impulsores/",
        views.Etapa5ImpulsoresView.as_view(),
        name="etapa5-impulsores",
    ),
    path("etapa5-testeos/", views.Etapa5testView.as_view(), name="etapa5-testeos"),
    path("etapa6/", views.Etapa6View.as_view(), name="etapa6"),
    path("etapa6-metodos/", views.Etapa6MetodosView.as_view(), name="etapa6-metodos"),
    path("etapa6-casos/", views.Etapa6CasosView.as_view(), name="etapa6-casos"),
    path("etapa7/", views.Etapa7View.as_view(), name="etapa7"),
    path(
        "etapa7-evaluacion/",
        views.Etapa7EvaluacionView.as_view(),
        name="etapa7-evaluacion",
    ),
    path(
        "etapa7-indicadores/",
        views.Etapa7IndicadoresView.as_view(),
        name="etapa7-indicadores",
    ),
    path("etapa7-exito/", views.Etapa7ExitosView.as_view(), name="etapa7-exito"),
    path("definicionedit/", views.Definicion1EditView.as_view(), name="definicionedit"),
    path("causasedit/", views.Causas2EditView.as_view(), name="causasedit"),
    path(
        "reflexionesedit/", views.ReflexionesEditView.as_view(), name="reflexionesedit"
    ),
    path(
        "mapaafinidadedit/",
        views.MapaAfinidad2EditView.as_view(),
        name="mapaafinidadedit",
    ),
    path(
        "oportunidadesedit/",
        views.OportunidadesEditView.as_view(),
        name="oportunidadesedit",
    ),
    path(
        "eventosedit/",
        views.EventosEditView.as_view(),
        name="eventosedit",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", views.logout_view, name="logout"),
    path("pdf1/", views.PDF1.as_view(), name="pdf1"),
    path("pdf2/", views.PDF2.as_view(), name="pdf2"),
    path("pdf3/", views.PDF3.as_view(), name="pdf3"),
    path("pdf4/", views.PDF4.as_view(), name="pdf4"),
    path("pdf5/", views.PDF5.as_view(), name="pdf5"),
    path("pdf6/", views.PDF6.as_view(), name="pdf6"),
]

democraciakit/democraciakit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_title = "DemocraciaKit"
admin.site.site_header = "DemocraciaKit"
admin.site.index_title = "DemocraciaKit panel"

urlpatterns = [
    path('paneldk/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('users.urls')),
    path('', include('contenidos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

democraciakit/users/urls.py
from django.urls import path
from . import views
from .forms import CustomAuthenticationForm

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password_reset/', views.password_reset, name='password_reset'),
]

htmx_urlpatterns = [
    path("check_username/", views.check_username, name="check_username"),
]

urlpatterns += htmx_urlpatterns

democraciakit/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=100)
    abreviatura = models.CharField(max_length=10)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Pais'
        verbose_name_plural = 'Paises'
        ordering = ['nombre']

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, null=True, blank=True)
    municipio = models.CharField(max_length=100, null=True, blank=True)
    foto = models.ImageField(upload_to='fotos/', null=True, blank=True)
    cargo = models.CharField(max_length=256, null=True, blank=True)
    frase = models.CharField(max_length=256, null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'
        ordering = ['email']

democraciakit/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from .models import Pais
from django.contrib.auth.forms import PasswordChangeForm

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'ldap_password' in self.fields:
            del self.fields['ldap_password']

    frase = forms.CharField(
        max_length=256,
        required=False,
        label='Apodo, nombre o frase',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa un apodo, nombre o frase que te caracterice'}),
    )
    email = forms.EmailField(
        max_length=254,
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ingresar email, este será tu nombre de usuari*'}),
    )
    password1 = forms.CharField(
        label='Contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ingresar contraseña'}),
    )
    password2 = forms.CharField(
        label='Confirmar contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Repetir contraseña'}),
    )
    pais = forms.ModelChoiceField(
        queryset=Pais.objects.all(),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    municipio = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa tu Municipio'}),
    )
    cargo = forms.CharField(
        max_length=256,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa tu cargo'}),
    )
    foto = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control'}),
    )
    descripcion = forms.CharField(
        max_length=500,
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingresa una descripción de tu trabajo'}),
    )

    class Meta:
        model = User
        fields = ['frase', 'email', 'password1', 'password2', 'pais', 'municipio', 'cargo', 'foto', 'descripcion']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este email ya está registrado.")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder': 'Email'}))
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}),
    )


# Formulario para cambiar la contraseña del usuario
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña actual'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nueva contraseña'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Repetir nueva contraseña'}))


# Formulario adicional para actualizar el perfil del usuario
class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'pais')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'pais': forms.Select(attrs={'class': 'form-control'}),
            'municipio': forms.TextInput(attrs={'class': 'form-control'}),
            'fotos': forms.FileInput(attrs={'class': 'form-control'}),
            'frase': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'})
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise ValidationError("Este email ya está en uso por otro usuario.")
        return email

democraciakit/users/views.py
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import (
    CustomUserCreationForm,
    CustomAuthenticationForm,
    CustomUserChangeForm,
)
from django.contrib.auth import update_session_auth_hash
from .forms import CustomPasswordChangeForm


def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("contenidos:index")
    else:
        form = CustomUserCreationForm()
    return render(request, "users/register.html", {"form": form})


def user_login(request):
    if request.method == "POST":
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("contenidos:index")
    else:
        form = CustomAuthenticationForm()
    return render(request, "users/user_login.html", {"form": form})


@login_required
def profile(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("users:profile")
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, "users/profile.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("contenidos:index")


def password_reset(request):
    if request.method == "POST":
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(
                request, user
            )  # Importante para mantener la sesión activa
            return redirect("contenidos:index")  # Redirige a una página de éxito
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, "users/password_reset.html", {"form": form})


def check_username(request):
    username = request.POST.get("username")
    if get_user_model().objects.filter(username=username).exists():
        return HttpResponse(
            "<div id='username-error' class='error'>This username is already taken</div>"
        )
    else:
        return HttpResponse(
            "<div id='username-error' class='success'>This username is available</div>"
        )

democraciakit/users/templates/users/1_password_reset-1.html
{% extends 'contenidos/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}DemocraciaKit - Cambiar contraseña{% endblock %}

{% block content %}

<main>
  
 <section class="accesos-directos">
    <a href="{% url 'contenidos:rueda' %}" class="btn-rueda">Rueda <img src="{% static 'img/icono-rueda.png' %}" class="icono" alt=""></a>
    <a href="#" class="btn-kit"><img src="{% static 'img/icono-kit.png' %}" class="icono" alt=""> Mi Kit</a>
  </section>
  <section class="container header-section">
    <div class="row">
      <div class="col-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'contenidos:rueda' %}">Rueda</a></li>
            <li class="breadcrumb-item active" aria-current="page">Registro</li>
          </ol>
        </nav>
        <h2>Cambiar contraseña</h2>
        <p></p>
      </div>
    </div>
  </section>
  <section class="container perfil form">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-6 col-lg-8">
        <form method="POST">
          {% csrf_token %} 
          {{ form|crispy }}
          <button class="btn-democraciakit mb-5" type="submit">Cambiar</button>
        </form>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4 panel">
        <!-- <div class="panel-control">
          <h4>Panel de control</h4>
          <div class="caja-rosada"></div>
          <div class="caja-verde"></div>
          </div> -->
      </div>
    </div>
  </section>
  <!-- <section class="premio">
    <div class="scrolling-text">
    <p class="text-white">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-blue">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-green">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-white">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-blue">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-green">Premio latinoamericano democracia digital 2da edición</p>
    </div>
    </section> -->
    <section class="descargar-toolkit-pdf">
      <div class="container">
        <div class="row">
          <div class="col-12 d-flex flex-row justify-content-center align-items-center align-self-center">
            <h4>Invitación a descargar Toolkit PDF</h4>
            <a href="https://drive.google.com/file/d/1l9rRNGLfrxYm-bzTBPYzd4XQD2U8aV6E/view" class="btn-democraciakit" target="_blank">Descargar</a>
          </div>
        </div>
      </div>
    </section>
</main>
{% endblock %}

democraciakit/users/templates/users/password_reset.html
{% extends 'contenidos/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}DemocraciaKit - Cambiar contraseña{% endblock %}

{% block content %}

<main>
  
 <section class="accesos-directos">
    <a href="{% url 'contenidos:rueda' %}" class="btn-rueda">Rueda <img src="{% static 'img/icono-rueda.png' %}" class="icono" alt=""></a>
    <a href="#" class="btn-kit"><img src="{% static 'img/icono-kit.png' %}" class="icono" alt=""> Mi Kit</a>
  </section>
  <section class="container header-section">
    <div class="row">
      <div class="col-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'contenidos:rueda' %}">Rueda</a></li>
            <li class="breadcrumb-item active" aria-current="page">Registro</li>
          </ol>
        </nav>
        <h2>Cambiar contraseña</h2>
        <p></p>
      </div>
    </div>
  </section>
  <section class="container perfil form">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-6 col-lg-8">
        <form method="POST">
          {% csrf_token %} 
          {{ form|crispy }}
          <button class="btn-democraciakit mb-5" type="submit">Cambiar</button>
        </form>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4 panel">
        <!-- <div class="panel-control">
          <h4>Panel de control</h4>
          <div class="caja-rosada"></div>
          <div class="caja-verde"></div>
          </div> -->
      </div>
    </div>
  </section>
  <!-- <section class="premio">
    <div class="scrolling-text">
    <p class="text-white">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-blue">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-green">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-white">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-blue">Premio latinoamericano democracia digital 2da edición</p>
    <p class="text-green">Premio latinoamericano democracia digital 2da edición</p>
    </div>
    </section> -->
    <section class="descargar-toolkit-pdf">
      <div class="container">
        <div class="row">
          <div class="col-12 d-flex flex-row justify-content-center align-items-center align-self-center">
            <h4>Invitación a descargar Toolkit PDF</h4>
            <a href="https://drive.google.com/file/d/1l9rRNGLfrxYm-bzTBPYzd4XQD2U8aV6E/view" class="btn-democraciakit" target="_blank">Descargar</a>
          </div>
        </div>
      </div>
    </section>
</main>
{% endblock %}

democraciakit/users/templates/users/profile.html
{% extends 'contenidos/base.html' %}
{% load static %}

{% block title %}DemocraciaKit - Perfil{% endblock %}
{% block content %}

<main>
    <section class="accesos-directos">
        <a href="{% url 'users:profile' %}" class="btn-rueda">Perfil <img src="{% static 'img/icono-perfil.png' %}" class="icono" alt="Entrar a mi perfil"></a>
        <a href="{% url 'contenidos:mikit' %}" class="btn-kit"><img src="{% static 'img/icono-kit.png' %}" class="icono" alt="Entrar a mi kit"> Mi Kit</a>
    </section>
    <section class="container header-section">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'contenidos:rueda' %}">Etapas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Perfil</li>
                    </ol>
                </nav>
                <h2>Mi Perfil</h2>
                <!-- <p>Frase descriptiva o que invite a completar el perfil</p> -->
            </div>
        </div>
    </section>
    <section class="container perfil form">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6 col-lg-8">
                    <div class="row">
                        <div class="col-12">
                            <h3>{{ user.username }}</h3>
                            {% if user.frase %}
                            <div class="frase mb-3">
                                <div class="bocadillo">
                                    <div class="forma"></div>
                                <!--    <textarea type="text" class="form-control form-frase" id="exampleFormControlTextarea1" rows="1" 
                                    placeholder="{{ user.frase }}" 
                                    aria-label="Frase descriptiva: {{ user.frase }}"></textarea> -->
                                </div>
                            </div>
                            {% endif %}
                        </div>
                        <div class="col-12 col-sm-12 col-md-5">
                            {% if user.foto %}
                            <img src="{{ user.foto.url }}" alt="Imagen de perfil del usuario" class="img-perfil mb-3 img-fluid">
                            {% else %}
                            {% endif %}
                        </div>
                        <!-- <div class="col-12 col-sm-12 col-md-7">
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Nombre usuario</label>
                                <p>{{ user.username }}</p>
                            </div>
                            {% if user.pais %}
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">País</label>
                                <p>{{ user.pais }}</p>
                            </div>
                            {% endif %}
                            {% if user.municipio %}
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Municipio</label>
                                <p>{{ user.municipio }}</p>
                            </div>
                            {% endif %}
                            {% if user.cargo %}
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Cargo</label>
                                <p>{{ user.cargo }}</p>
                            </div>
                            {% endif %}
                        </div> -->
                    </div>
                    <div class="row">
                        {% if user.descripcion %}
                        <div class="col-12 mb-3">
                            <label for="exampleInputEmail1" class="form-label">Descripción</label>
                            <p>{{ user.descripcion }}</p>
                        </div>
                        {% endif %}
                    </div>
            </div>
    </section>

</main>


{% endblock %}

democraciakit/users/templates/users/register.html
{% extends 'contenidos/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Registrarse{% endblock %}

{% block content %}

<main>

        <section class="accesos-directos">
        <a href="{% url 'contenidos:rueda' %}" class="btn-rueda">Etapas <img src="{% static 'img/icono-rueda.png' %}" class="icono" alt=""></a>
        <a href="#" class="btn-kit"><img src="{% static 'img/icono-kit.png' %}" class="icono" alt=""> Mi Kit</a>
    </section>
    <section class="container header-section">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'contenidos:rueda' %}">Etapas</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Registro</li>
                    </ol>
                </nav>
                <h2>Registro</h2>
                <p>Completa todos los campos para crear tu cuenta e ingresar a DemocraciaKit</p>
                <p>¡Sólo los campos con * son requeridos!, pero nos gustaría saber más de ti</p>
                <p>¡Si tienes tiempo completalos todos!</p>
            </div>
        </div>
    </section>
    <section class="container perfil form">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6 col-lg-8">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <button type="submit" class="btn-democraciakit mb-5">Guardar</button>
                </form>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 panel">
                <!-- <div class="cambiar-contrasena">
                    <p>¿Quieres cambiar la contraseña?</p>
                    <a href="{% url 'users:password_reset' %}" class="btn-democraciakit btn-rosado">Cambiar contraseña</a>
                </div> -->
                <div class="mb-3 recuperar">
                    <p><a href="{% url 'contenidos:derechos' %}">Protegemos tu privacidad y seguridad</a></p>
                </div>

            </div>
        </div>
    </section>

    <section class="descargar-toolkit-pdf">
        <div class="container">

            </div>
        </div>
    </section>

    <section class="descargar-toolkit-pdf">
        <div class="container">
            <div class="row">
                <div class="col-12 d-flex flex-row justify-content-center align-items-center align-self-center">
                    <h4>Invitación a descargar Toolkit PDF</h4>
                    <a href="https://drive.google.com/file/d/1l9rRNGLfrxYm-bzTBPYzd4XQD2U8aV6E/view" class="btn-democraciakit" target="_blank">Descargar</a>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

democraciakit/users/templates/users/user_login.html
{% extends 'contenidos/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Iniciar Sesión{% endblock %}

{% block content %}

<main>
    <section class="container-fluid login form">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-6 col-lg-6">
                    <h2>Iniciar sesión</h2>
                    <p>Un viaje a través de <span>múltiples herramientas</span> que permiten el diseño de un proyecto participativo.</p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Usuario o correo</label>
                            <input type="email" class="form-control" id="username" name="username" aria-describedby="emailHelp" placeholder="Ingresa aquí">
                            <div id="emailHelp" class="form-text">ejemplo@correo.com</div>
                        </div>
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña">
                        </div>
                        <button type="submit" class="btn-democraciakit mb-5">Entrar</button>
                    </form>
                    <div class="mb-3 recuperar">
                        <p>¿Aún no te has registrado? <a href="{% url 'users:register' %}">&gt; hazlo aquí</a></p>
                    </div>
                    <div class="mb-3 recuperar">
                        <p><a href="{% url 'contenidos:derechos' %}">Protegemos tu privacidad y seguridad</a></p>
                    </div>
                    <!-- <div class="mb-3 recuperar">
                        <p>¿Olvidaste tu contraseña? <a href="{% url 'users:password_reset' %}" class="enlace-recuperar">&gt; Recuperar aquí</a></p>
                    </div> -->
                </div>
            </div>
        </div>
        <div class="img-decoracion">
            <img src="{% static 'img/rueda-mitad-decoracion.png' %}" alt="" class="img-decoracion-desktop" />
        </div>
    </section>
</main>
{% endblock %}