democraciakit/contenidos/urls.py
from django.urls import path, include
from . import views
from .views import *

app_name = "contenidos"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("mikit/", views.MikitView.as_view(), name="mikit"),
    path("derechos/", views.DerechosView.as_view(), name="derechos"),
    path("rueda/", views.RuedaView.as_view(), name="rueda"),
    path("etapa1/", views.Etapa1View.as_view(), name="etapa1"),
    path("quees/", views.QueesView.as_view(), name="quees"),
    path("inicio/", views.InicioView.as_view(), name="inicio"),
    path(
        "etapa1-conceptos/",
        views.Etapa1ConceptosView.as_view(),
        name="etapa1-conceptos",
    ),
    path(
        "etapa1-definicion/",
        views.Definicion1CreateView.as_view(),
        name="etapa1-definicion",
    ),
    path(
        "etapa1-estrategia/",
        views.Etapa1EstrategiaView.as_view(),
        name="etapa1-estrategia",
    ),
    path("etapa1-sesgo/", views.Etapa1SesgoView.as_view(), name="etapa1-sesgo"),
    path("etapa2/", views.Etapa2View.as_view(), name="etapa2"),
    path("etapa2-matriz/", views.Etapa2MatrizView.as_view(), name="etapa2-matriz"),
    path(
        "etapa2-mapaafinidad/",
        views.MapaAfinidad2CreateView.as_view(),
        name="etapa2-mapaafinidad",
    ),
    path(
        "etapa2-inclusivo/",
        views.Inclusivo2CreateView.as_view(),
        name="etapa2-inclusivo",
    ),
    path(
        "etapa2-identificacion/",
        views.IdentificacionCreateView.as_view(),
        name="etapa2-identificacion",
    ),
    path("etapa3/", views.Etapa3View.as_view(), name="etapa3"),
    path("etapa3-3x3x3/", views.Etapa33x3x3View.as_view(), name="etapa3-3x3x3"),
    path(
        "etapa3-sombreros/",
        views.Etapa3SombrerosView.as_view(),
        name="etapa3-sombreros",
    ),
    path(
        "etapa3-reflexionar/",
        views.Etapa3ReflexionarView.as_view(),
        name="etapa3-reflexionar",
    ),
    path("etapa3-smart/", views.Etapa3SmartView.as_view(), name="etapa3-smart"),
    path("etapa4/", views.Etapa4View.as_view(), name="etapa4"),
    path(
        "etapa4-proyeccion/",
        views.Etapa4ProyeccionView.as_view(),
        name="etapa4-proyeccion",
    ),
    path(
        "etapa4-mapaactores/",
        views.Etapa4MapaactoresView.as_view(),
        name="etapa4-mapaactores",
    ),
    path("etapa4-eventos/", views.Etapa4EventosView.as_view(), name="etapa4-eventos"),
    path(
        "etapa4-oportunidades/",
        views.Etapa4OportunidadesView.as_view(),
        name="etapa4-oportunidades",
    ),
    path(
        "etapa4-plandetrabajo/",
        views.Etapa4PlandetrabajoView.as_view(),
        name="etapa4-plandetrabajo",
    ),
    path("etapa5/", views.Etapa5View.as_view(), name="etapa5"),
    path(
        "etapa5-keepfixtry/",
        views.Etapa5KeepfixtryView.as_view(),
        name="etapa5-keepfixtry",
    ),
    path(
        "etapa5-impulsores/",
        views.Etapa5ImpulsoresView.as_view(),
        name="etapa5-impulsores",
    ),
    path("etapa5-testeos/", views.Etapa5testView.as_view(), name="etapa5-testeos"),
    path("etapa6/", views.Etapa6View.as_view(), name="etapa6"),
    path("etapa6-metodos/", views.Etapa6MetodosView.as_view(), name="etapa6-metodos"),
    path("etapa6-casos/", views.Etapa6CasosView.as_view(), name="etapa6-casos"),
    path("etapa7/", views.Etapa7View.as_view(), name="etapa7"),
    path(
        "etapa7-evaluacion/",
        views.Etapa7EvaluacionView.as_view(),
        name="etapa7-evaluacion",
    ),
    path(
        "etapa7-indicadores/",
        views.Etapa7IndicadoresView.as_view(),
        name="etapa7-indicadores",
    ),
    path("etapa7-exito/", views.Etapa7ExitosView.as_view(), name="etapa7-exito"),
    path("definicionedit/", views.Definicion1EditView.as_view(), name="definicionedit"),
    path("causasedit/", views.Causas2EditView.as_view(), name="causasedit"),
    path(
        "reflexionesedit/", views.ReflexionesEditView.as_view(), name="reflexionesedit"
    ),
    path(
        "mapaafinidadedit/",
        views.MapaAfinidad2EditView.as_view(),
        name="mapaafinidadedit",
    ),
    path(
        "oportunidadesedit/",
        views.OportunidadesEditView.as_view(),
        name="oportunidadesedit",
    ),
    path(
        "eventosedit/",
        views.EventosEditView.as_view(),
        name="eventosedit",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", views.logout_view, name="logout"),
    path("pdf1/", views.PDF1.as_view(), name="pdf1"),
    path("pdf2/", views.PDF2.as_view(), name="pdf2"),
    path("pdf3/", views.PDF3.as_view(), name="pdf3"),
    path("pdf4/", views.PDF4.as_view(), name="pdf4"),
    path("pdf5/", views.PDF5.as_view(), name="pdf5"),
    path("pdf6/", views.PDF6.as_view(), name="pdf6"),
]

democraciakit/democraciakit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_title = "DemocraciaKit"
admin.site.site_header = "DemocraciaKit"
admin.site.index_title = "DemocraciaKit panel"

urlpatterns = [
    path('paneldk/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('users.urls')),
    path('', include('contenidos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

democraciakit/users/urls.py
from django.urls import path
from . import views
from .forms import CustomAuthenticationForm

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password_reset/', views.password_reset, name='password_reset'),
]

htmx_urlpatterns = [
    path("check_username/", views.check_username, name="check_username"),
]

urlpatterns += htmx_urlpatterns

democraciakit/contenidos/views.py
from django.shortcuts import reverse, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import FormView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout, authenticate
from django.views.generic import DetailView
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.http import Http404

User = get_user_model()


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "contenidos/index.html"
    redirect_field_name = "contenidos/index.html"


class InicioView(TemplateView):
    template_name = "contenidos/inicio.html"


class DerechosView(TemplateView):
    template_name = "contenidos/derechos.html"


class QueesView(TemplateView):
    template_name = "contenidos/partials/quees.html"


class MikitView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/mikit.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["definicion1_usuarios"] = (
            self.object.definicion1_usuarios.all().order_by("-fecha_definicion1")
        )
        context["formulario_reciente1"] = self.object.definicion1_usuarios.order_by(
            "-fecha_definicion1"
        ).first()

        context["causas2_usuarios"] = self.object.causas2_usuarios.all().order_by(
            "-fecha_causas2"
        )
        context["formulario_reciente2"] = self.object.causas2_usuarios.order_by(
            "-fecha_causas2"
        ).first()

        context["inclusivo2_usuarios"] = self.object.inclusivo2_usuarios.all().order_by(
            "-fecha_inclusivo2"
        )
        context["formulario_reciente3"] = self.object.inclusivo2_usuarios.order_by(
            "-fecha_inclusivo2"
        ).first()

        context["mapadeafinidad2_usuarios"] = (
            self.object.mapadeafinidad2_usuarios.all().order_by("-fecha_mapadeafinidad2")
        )
        context["formulario_reciente4"] = self.object.mapadeafinidad2_usuarios.order_by(
            "-fecha_mapadeafinidad2"
        ).first()

        context["oportunidades4_usuarios"] = (
            self.object.oportunidades4_usuarios.all().order_by("-fecha_oportunidades4")
        )
        context["formulario_reciente41"] = self.object.oportunidades4_usuarios.order_by(
            "-fecha_oportunidades4"
        ).first()

        context["eventos4_usuarios"] = self.object.eventos4_usuarios.all().order_by(
            "-fecha_eventos4"
        )
        context["formulario_reciente42"] = self.object.eventos4_usuarios.order_by(
            "-fecha_eventos4"
        ).first()

        return context


class PDF1(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf1.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["definicion1_usuarios"] = (
            self.object.definicion1_usuarios.all().order_by("-fecha_definicion1")
        )
        context["formulario_reciente1"] = self.object.definicion1_usuarios.order_by(
            "-fecha_definicion1"
        ).first()

        return context


class PDF2(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf2.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["causas2_usuarios"] = self.object.causas2_usuarios.all().order_by(
            "-fecha_causas2"
        )
        context["formulario_reciente2"] = self.object.causas2_usuarios.order_by(
            "-fecha_causas2"
        ).first()

        return context


class PDF3(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf3.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["inclusivo2_usuarios"] = self.object.inclusivo2_usuarios.all().order_by(
            "-fecha_inclusivo2"
        )
        context["formulario_reciente3"] = self.object.inclusivo2_usuarios.order_by(
            "-fecha_inclusivo2"
        ).first()

        return context


class PDF4(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf4.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mapadeafinidad2_usuarios"] = (
            self.object.mapadeafinidad2_usuarios.all().order_by("-fecha_mapadeafinidad2")
        )
        context["formulario_reciente4"] = self.object.mapadeafinidad2_usuarios.order_by(
            "-fecha_mapadeafinidad2"
        ).first()

        return context


class PDF5(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf5.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["oportunidades4_usuarios"] = (
            self.object.oportunidades4_usuarios.all().order_by("-fecha_oportunidades4")
        )
        context["formulario_reciente41"] = self.object.oportunidades4_usuarios.order_by(
            "-fecha_oportunidades4"
        ).first()

        return context


class PDF6(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf6.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["eventos4_usuarios"] = self.object.eventos4_usuarios.all().order_by(
            "-fecha_eventos4"
        )
        context["formulario_reciente42"] = self.object.eventos4_usuarios.order_by(
            "-fecha_eventos4"
        ).first()

        return context


class Definicion1EditView(FormView):
    form_class = Definicion1Edit
    template_name = "contenidos/partials/definicionedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap1"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class Causas2EditView(FormView):
    form_class = Causas2Edit
    template_name = "contenidos/partials/causasedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap2"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class ReflexionesEditView(FormView):
    form_class = Inclusivo2Edit
    template_name = "contenidos/partials/reflexionesedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap3"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class MapaAfinidad2EditView(FormView):
    form_class = Mapadeafinidad2Edit
    template_name = "contenidos/partials/mapaafinidadedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap4"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class OportunidadesEditView(FormView):
    form_class = Oportunidades2Edit
    template_name = "contenidos/partials/oportunidades.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap5"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class EventosEditView(FormView):
    form_class = Eventos4Edit
    template_name = "contenidos/partials/eventosedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap6"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class RuedaView(TemplateView):
    template_name = "contenidos/rueda.html"


class Etapa1View(TemplateView):
    template_name = "contenidos/etapa1.html"


class Etapa1ConceptosView(TemplateView):
    template_name = "contenidos/etapa1-conceptos.html"


class Definicion1CreateView(FormView):
    form_class = Definicion1Form
    template_name = "contenidos/etapa1-definicion.html"
    success_url = reverse_lazy("contenidos:etapa1-definicion")

democraciakit/contenidos/templates/contenidos/partials/causasedit.html
{% load crispy_forms_tags %}

    <div id="modal" class="modal modal-dialog-center" _="on closeModal add .closing then wait for animationend then remove me">
        <div class="modal-content modal-dialog-scrollable" role="document">
            <h4 class="metodologias">Edita las causas de tu problema</h4>
            <form action="{% url 'contenidos:causasedit' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button 
                class="btn-democraciakit"
                hx-post="{% url 'contenidos:mikit' %}"
                hx-trigger="submit"
                hx-target="#swap2"
                hx-swap="afterend">Guardar</button>
            </form>
            <br> 
            <p>Debes completar todas las causas para que queden guardadas correctamente.</p>
            <div class="modal-footer">  
            <button class="btn-editar-metodologias" _="on click trigger closeModal">Cerrar</button>
           </div>
        </div>
    </div>

democraciakit/contenidos/templates/contenidos/partials/definicion1.html
{% load crispy_forms_tags %}


    <div id="modal" class="modal modal-dialog-center" _="on closeModal add .closing then wait for animationend then remove me">
        <div class="modal-content modal-dialog-scrollable" role="document">
            <h4 class="metodologias">Revisa tu defición</h4>
            {% if formulario_reciente1 %}
            <h4>Quién:</h4> <p>{{ formulario_reciente1.uno|linebreaks }}</p>
            <h4>Dónde:</h4> <p>{{ formulario_reciente1.dos|linebreaks }}</p>
            <h4>Cuando:</h4><p>{{ formulario_reciente1.tres|linebreaks }}</p>
            <h4>Dolor:</h4> <p>{{ formulario_reciente1.cuatro|linebreaks }}</p>
            {% endif %}
            <br>
            <button class="btn-editar-metodologias" hx-get="{% url 'contenidos:definicionedit' %}" hx-target="#swap1" hx-swap="innerHTML">Editar definiciones</button> 
            <div class="modal-footer">
            <button class="btn-editar-metodologias" _="on click trigger closeModal">Cerrar</button>
           </div>
        </div>
    </div>

democraciakit/contenidos/templates/contenidos/partials/definicionedit.html
{% load crispy_forms_tags %}

    <div id="modal" class="modal modal-dialog-center" _="on closeModal add .closing then wait for animationend then remove me">
        <div class="modal-content modal-dialog-scrollable" role="document">
            <h4 class="metodologias">Edita tu defición</h4>
            <form action="{% url 'contenidos:definicionedit' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button 
                class="btn-democraciakit"
                hx-post="{% url 'contenidos:mikit' %}"
                hx-trigger="submit"
                hx-target="#swap1"
                hx-swap="afterend">Guardar</button>
            </form>
            <br> 
            <p>Debes completar todas las definiciones para que queden guardadas correctamente.</p>
            <div class="modal-footer">  
            <button class="btn-editar-metodologias" _="on click trigger closeModal">Cerrar</button>
           </div>
        </div>
    </div>

democraciakit/contenidos/templates/contenidos/partials/definicionedit2.html
{% load crispy_forms_tags %}

    <div id="modal" class="modal modal-dialog-center" _="on closeModal add .closing then wait for animationend then remove me">
        <div class="modal-content modal-dialog-scrollable" role="document">
            <h4 class="metodologias">Edita tu defición</h4>
            <form action="{% url 'contenidos:definicionedit' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button 
                class="btn-democraciakit"
                hx-post="{% url 'contenidos:mikit' %}"
                hx-trigger="submit"
                hx-target="#swap1"
                hx-swap="afterend">Guardar</button>
            </form>
            <br> 
            <div class="modal-footer">  
            <button class="btn-editar-metodologias" _="on click trigger closeModal">Cerrar</button>
           </div>
        </div>
    </div>

democraciakit/contenidos/templates/contenidos/partials/eventosedit.html
{% load crispy_forms_tags %}

<div
  id="modal"
  class="modal modal-dialog-center"
  _="on closeModal add .closing then wait for animationend then remove me"
>
  <div class="modal-content modal-dialog-scrollable" role="document">
    <h4 class="metodologias">Edita eventos y acciones</h4>
    <form action="{% url 'contenidos:eventosedit' %}" method="post">
      {% csrf_token %} {{ form|crispy }}
      <button
        class="btn-democraciakit"
        hx-post="{% url 'contenidos:mikit' %}"
        hx-trigger="submit"
        hx-target="#swap5"
        hx-swap="afterend"
      >
        Guardar
      </button>
    </form>
    <br />
    <p>
      Debes completar todas los elementos para que queden guardados
      correctamente.
    </p>
    <div class="modal-footer">
      <button class="btn-editar-metodologias" _="on click trigger closeModal">
        Cerrar
      </button>
    </div>
  </div>
</div>

democraciakit/contenidos/templates/contenidos/partials/mapaafinidadedit.html
{% load crispy_forms_tags %}

<div
  id="modal"
  class="modal modal-dialog-center"
  _="on closeModal add .closing then wait for animationend then remove me"
>
  <div class="modal-content modal-dialog-scrollable" role="document">
    <h4 class="metodologias">Edita tu mapa de afinidad </h4>
    <form action="{% url 'contenidos:mapaafinidadedit' %}" method="post">
      {% csrf_token %} {{ form|crispy }}
      <button
        class="btn-democraciakit"
        hx-post="{% url 'contenidos:mikit' %}"
        hx-trigger="submit"
        hx-target="#swap4"
        hx-swap="afterend"
      >
        Guardar
      </button>
    </form>
    <br />
    <p>
      Debes completar todas los elementos para que queden guardados correctamente.
    </p>
    <div class="modal-footer">
      <button class="btn-editar-metodologias" _="on click trigger closeModal">
        Cerrar
      </button>
    </div>
  </div>
</div>

democraciakit/contenidos/templates/contenidos/partials/oportunidades.html
{% load crispy_forms_tags %}

<div
  id="modal"
  class="modal modal-dialog-center"
  _="on closeModal add .closing then wait for animationend then remove me"
>
  <div class="modal-content modal-dialog-scrollable" role="document">
    <h4 class="metodologias">Edita tus oportunidades y amenazas</h4>
    <form action="{% url 'contenidos:oportunidadesedit' %}" method="post">
      {% csrf_token %} {{ form|crispy }}
      <button
        class="btn-democraciakit"
        hx-post="{% url 'contenidos:mikit' %}"
        hx-trigger="submit"
        hx-target="#swap5"
        hx-swap="afterend"
      >
        Guardar
      </button>
    </form>
    <br />
    <p>
      Debes completar todas los elementos para que queden guardados
      correctamente.
    </p>
    <div class="modal-footer">
      <button class="btn-editar-metodologias" _="on click trigger closeModal">
        Cerrar
      </button>
    </div>
  </div>
</div>

democraciakit/contenidos/templates/contenidos/partials/quees.html
<div
  id="modal"
  class="modal modal-dialog-center"
  _="on closeModal add .closing then wait for animationend then remove me"
>
  <div class="modal-content modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h3>¿Qué encontraré aquí?</h3>
        <p>
          Un viaje a través de <b>múltiples herramientas</b> que permiten el
          diseño de un proyecto participativo.
        </p>
        <h3 class="titular-destacado">
          <span class="bg-verde"
            >¡Explora cómo involucrar a la ciudadanía en cada etapa del
            proceso!</span
          >
        </h3>
        <h3>¿Por qué es necesario?</h3>
        <p>
          Para fortalecer las democracias en Latinoamérica y el Caribe es
          necesario que las demandas ciudadanas sean escuchadas y transformadas
          en decisiones públicas. Para esto, se vuelve urgente capacitar a
          distintos actores territoriales con herramientas que les permitan:
        </p>
        <ul>
          <li>
            <p>
              Promover una gestión pública participativa, abierta e innovadora.
            </p>
          </li>
          <li>
            <p>
              Organizar demandas sociales e impulsarlas en el espacio público
              utilizando diversas acciones para la incidencia.
            </p>
          </li>
          <li>
            <p>Construir capacidad de fiscalización ciudadana.</p>
          </li>
        </ul>
        <div class="cta">
          <h4 class="color-rosado">¡Comienza el viaje!</h4>
          <a href="{% url 'users:user_login' %}" class="btn-democraciakit"
            >Ir a DemocraciaKit</a
          >
          <div class="align-items-center">
            <br /><br />
            <button
              class="btn-editar-metodologias"
              _="on click trigger closeModal"
            >
              Cerrar
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

democraciakit/contenidos/templates/contenidos/partials/reflexionesedit.html
{% load crispy_forms_tags %}

    <div id="modal" class="modal modal-dialog-center" _="on closeModal add .closing then wait for animationend then remove me">
        <div class="modal-content modal-dialog-scrollable" role="document">
            <h4 class="metodologias">Edita tus reflexiones sobre inclusividad</h4>
            <form action="{% url 'contenidos:reflexionesedit' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button 
                class="btn-democraciakit"
                hx-post="{% url 'contenidos:mikit' %}"
                hx-trigger="submit"
                hx-target="#swap3"
                hx-swap="afterend">Guardar</button>
            </form>
            <br> 
            <p>Debes completar todas las reflexiones para que queden guardadas correctamente.</p>
            <div class="modal-footer">  
            <button class="btn-editar-metodologias" _="on click trigger closeModal">Cerrar</button>
           </div>
        </div>
    </div>