democraciakit/contenidos/urls.py
from django.urls import path, include
from . import views
from .views import *

app_name = "contenidos"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("mikit/", views.MikitView.as_view(), name="mikit"),
    path("derechos/", views.DerechosView.as_view(), name="derechos"),
    path("rueda/", views.RuedaView.as_view(), name="rueda"),
    path("etapa1/", views.Etapa1View.as_view(), name="etapa1"),
    path("quees/", views.QueesView.as_view(), name="quees"),
    path("inicio/", views.InicioView.as_view(), name="inicio"),
    path(
        "etapa1-conceptos/",
        views.Etapa1ConceptosView.as_view(),
        name="etapa1-conceptos",
    ),
    path(
        "etapa1-definicion/",
        views.Definicion1CreateView.as_view(),
        name="etapa1-definicion",
    ),
    path(
        "etapa1-estrategia/",
        views.Etapa1EstrategiaView.as_view(),
        name="etapa1-estrategia",
    ),
    path("etapa1-sesgo/", views.Etapa1SesgoView.as_view(), name="etapa1-sesgo"),
    path("etapa2/", views.Etapa2View.as_view(), name="etapa2"),
    path("etapa2-matriz/", views.Etapa2MatrizView.as_view(), name="etapa2-matriz"),
    path(
        "etapa2-mapaafinidad/",
        views.MapaAfinidad2CreateView.as_view(),
        name="etapa2-mapaafinidad",
    ),
    path(
        "etapa2-inclusivo/",
        views.Inclusivo2CreateView.as_view(),
        name="etapa2-inclusivo",
    ),
    path(
        "etapa2-identificacion/",
        views.IdentificacionCreateView.as_view(),
        name="etapa2-identificacion",
    ),
    path("etapa3/", views.Etapa3View.as_view(), name="etapa3"),
    path("etapa3-3x3x3/", views.Etapa33x3x3View.as_view(), name="etapa3-3x3x3"),
    path(
        "etapa3-sombreros/",
        views.Etapa3SombrerosView.as_view(),
        name="etapa3-sombreros",
    ),
    path(
        "etapa3-reflexionar/",
        views.Etapa3ReflexionarView.as_view(),
        name="etapa3-reflexionar",
    ),
    path("etapa3-smart/", views.Etapa3SmartView.as_view(), name="etapa3-smart"),
    path("etapa4/", views.Etapa4View.as_view(), name="etapa4"),
    path(
        "etapa4-proyeccion/",
        views.Etapa4ProyeccionView.as_view(),
        name="etapa4-proyeccion",
    ),
    path(
        "etapa4-mapaactores/",
        views.Etapa4MapaactoresView.as_view(),
        name="etapa4-mapaactores",
    ),
    path("etapa4-eventos/", views.Etapa4EventosView.as_view(), name="etapa4-eventos"),
    path(
        "etapa4-oportunidades/",
        views.Etapa4OportunidadesView.as_view(),
        name="etapa4-oportunidades",
    ),
    path(
        "etapa4-plandetrabajo/",
        views.Etapa4PlandetrabajoView.as_view(),
        name="etapa4-plandetrabajo",
    ),
    path("etapa5/", views.Etapa5View.as_view(), name="etapa5"),
    path(
        "etapa5-keepfixtry/",
        views.Etapa5KeepfixtryView.as_view(),
        name="etapa5-keepfixtry",
    ),
    path(
        "etapa5-impulsores/",
        views.Etapa5ImpulsoresView.as_view(),
        name="etapa5-impulsores",
    ),
    path("etapa5-testeos/", views.Etapa5testView.as_view(), name="etapa5-testeos"),
    path("etapa6/", views.Etapa6View.as_view(), name="etapa6"),
    path("etapa6-metodos/", views.Etapa6MetodosView.as_view(), name="etapa6-metodos"),
    path("etapa6-casos/", views.Etapa6CasosView.as_view(), name="etapa6-casos"),
    path("etapa7/", views.Etapa7View.as_view(), name="etapa7"),
    path(
        "etapa7-evaluacion/",
        views.Etapa7EvaluacionView.as_view(),
        name="etapa7-evaluacion",
    ),
    path(
        "etapa7-indicadores/",
        views.Etapa7IndicadoresView.as_view(),
        name="etapa7-indicadores",
    ),
    path("etapa7-exito/", views.Etapa7ExitosView.as_view(), name="etapa7-exito"),
    path("definicionedit/", views.Definicion1EditView.as_view(), name="definicionedit"),
    path("causasedit/", views.Causas2EditView.as_view(), name="causasedit"),
    path(
        "reflexionesedit/", views.ReflexionesEditView.as_view(), name="reflexionesedit"
    ),
    path(
        "mapaafinidadedit/",
        views.MapaAfinidad2EditView.as_view(),
        name="mapaafinidadedit",
    ),
    path(
        "oportunidadesedit/",
        views.OportunidadesEditView.as_view(),
        name="oportunidadesedit",
    ),
    path(
        "eventosedit/",
        views.EventosEditView.as_view(),
        name="eventosedit",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", views.logout_view, name="logout"),
    path("pdf1/", views.PDF1.as_view(), name="pdf1"),
    path("pdf2/", views.PDF2.as_view(), name="pdf2"),
    path("pdf3/", views.PDF3.as_view(), name="pdf3"),
    path("pdf4/", views.PDF4.as_view(), name="pdf4"),
    path("pdf5/", views.PDF5.as_view(), name="pdf5"),
    path("pdf6/", views.PDF6.as_view(), name="pdf6"),
]

democraciakit/democraciakit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_title = "DemocraciaKit"
admin.site.site_header = "DemocraciaKit"
admin.site.index_title = "DemocraciaKit panel"

urlpatterns = [
    path('paneldk/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('users.urls')),
    path('', include('contenidos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

democraciakit/users/urls.py
from django.urls import path
from . import views
from .forms import CustomAuthenticationForm

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password_reset/', views.password_reset, name='password_reset'),
]

htmx_urlpatterns = [
    path("check_username/", views.check_username, name="check_username"),
]

urlpatterns += htmx_urlpatterns

democraciakit/contenidos/views.py
from django.shortcuts import reverse, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import FormView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout, authenticate
from django.views.generic import DetailView
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.http import Http404

User = get_user_model()


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "contenidos/index.html"
    redirect_field_name = "contenidos/index.html"


class InicioView(TemplateView):
    template_name = "contenidos/inicio.html"


class DerechosView(TemplateView):
    template_name = "contenidos/derechos.html"


class QueesView(TemplateView):
    template_name = "contenidos/partials/quees.html"


class MikitView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/mikit.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["definicion1_usuarios"] = (
            self.object.definicion1_usuarios.all().order_by("-fecha_definicion1")
        )
        context["formulario_reciente1"] = self.object.definicion1_usuarios.order_by(
            "-fecha_definicion1"
        ).first()

        context["causas2_usuarios"] = self.object.causas2_usuarios.all().order_by(
            "-fecha_causas2"
        )
        context["formulario_reciente2"] = self.object.causas2_usuarios.order_by(
            "-fecha_causas2"
        ).first()

        context["inclusivo2_usuarios"] = self.object.inclusivo2_usuarios.all().order_by(
            "-fecha_inclusivo2"
        )
        context["formulario_reciente3"] = self.object.inclusivo2_usuarios.order_by(
            "-fecha_inclusivo2"
        ).first()

        context["mapadeafinidad2_usuarios"] = (
            self.object.mapadeafinidad2_usuarios.all().order_by("-fecha_mapadeafinidad2")
        )
        context["formulario_reciente4"] = self.object.mapadeafinidad2_usuarios.order_by(
            "-fecha_mapadeafinidad2"
        ).first()

        context["oportunidades4_usuarios"] = (
            self.object.oportunidades4_usuarios.all().order_by("-fecha_oportunidades4")
        )
        context["formulario_reciente41"] = self.object.oportunidades4_usuarios.order_by(
            "-fecha_oportunidades4"
        ).first()

        context["eventos4_usuarios"] = self.object.eventos4_usuarios.all().order_by(
            "-fecha_eventos4"
        )
        context["formulario_reciente42"] = self.object.eventos4_usuarios.order_by(
            "-fecha_eventos4"
        ).first()

        return context


class PDF1(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf1.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["definicion1_usuarios"] = (
            self.object.definicion1_usuarios.all().order_by("-fecha_definicion1")
        )
        context["formulario_reciente1"] = self.object.definicion1_usuarios.order_by(
            "-fecha_definicion1"
        ).first()

        return context


class PDF2(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf2.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["causas2_usuarios"] = self.object.causas2_usuarios.all().order_by(
            "-fecha_causas2"
        )
        context["formulario_reciente2"] = self.object.causas2_usuarios.order_by(
            "-fecha_causas2"
        ).first()

        return context


class PDF3(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf3.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["inclusivo2_usuarios"] = self.object.inclusivo2_usuarios.all().order_by(
            "-fecha_inclusivo2"
        )
        context["formulario_reciente3"] = self.object.inclusivo2_usuarios.order_by(
            "-fecha_inclusivo2"
        ).first()

        return context


class PDF4(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf4.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mapadeafinidad2_usuarios"] = (
            self.object.mapadeafinidad2_usuarios.all().order_by("-fecha_mapadeafinidad2")
        )
        context["formulario_reciente4"] = self.object.mapadeafinidad2_usuarios.order_by(
            "-fecha_mapadeafinidad2"
        ).first()

        return context


class PDF5(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf5.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["oportunidades4_usuarios"] = (
            self.object.oportunidades4_usuarios.all().order_by("-fecha_oportunidades4")
        )
        context["formulario_reciente41"] = self.object.oportunidades4_usuarios.order_by(
            "-fecha_oportunidades4"
        ).first()

        return context


class PDF6(LoginRequiredMixin, DetailView):
    model = User
    template_name = "contenidos/pdf6.html"
    context_object_name = "usuario"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["eventos4_usuarios"] = self.object.eventos4_usuarios.all().order_by(
            "-fecha_eventos4"
        )
        context["formulario_reciente42"] = self.object.eventos4_usuarios.order_by(
            "-fecha_eventos4"
        ).first()

        return context


class Definicion1EditView(FormView):
    form_class = Definicion1Edit
    template_name = "contenidos/partials/definicionedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap1"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class Causas2EditView(FormView):
    form_class = Causas2Edit
    template_name = "contenidos/partials/causasedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap2"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class ReflexionesEditView(FormView):
    form_class = Inclusivo2Edit
    template_name = "contenidos/partials/reflexionesedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap3"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class MapaAfinidad2EditView(FormView):
    form_class = Mapadeafinidad2Edit
    template_name = "contenidos/partials/mapaafinidadedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap4"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class OportunidadesEditView(FormView):
    form_class = Oportunidades2Edit
    template_name = "contenidos/partials/oportunidades.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap5"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class EventosEditView(FormView):
    form_class = Eventos4Edit
    template_name = "contenidos/partials/eventosedit.html"

    def get_success_url(self):
        return reverse("contenidos:mikit") + "#swap6"

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # Guarda el formulario
        form.save()
        # Añade un mensaje de éxito
        messages.success(self.request, "¡Se han guardado tus definiciones!")
        return super().form_valid(form)


class RuedaView(TemplateView):
    template_name = "contenidos/rueda.html"


class Etapa1View(TemplateView):
    template_name = "contenidos/etapa1.html"


class Etapa1ConceptosView(TemplateView):
    template_name = "contenidos/etapa1-conceptos.html"


class Definicion1CreateView(FormView):
    form_class = Definicion1Form
    template_name = "contenidos/etapa1-definicion.html"
    success_url = reverse_lazy("contenidos:etapa1-definicion")

democraciakit/contenidos/templates/contenidos/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Democraciakit una guía práctica e interactiva creada para ayudar a personas líderes innovadores públicos a potenciar la participación ciudadana y fortalecer la democracia local en América Latina.">
    <meta name="keywords" content="Democraciakit, herramienta interactiva, participación, democracia, ciudadanía, América Latina, Latam, Latinoamérica, latinoamérica, Kit, kit, kit de democracia, Fundación Ciudadnía Inteligente, FCI, Abre Alcaldías">
    <title>FCI - {% block title %}{% endblock %}</title>
    <meta name="robots" content="index, follow">
    <meta name="theme-color" content="#000F74">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Hoja de estilos css-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- Favicon-->
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">

    <!-- Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Font icons google-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- Font awesome-->
    <script src="https://kit.fontawesome.com/791853223d.js" crossorigin="anonymous"></script>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-DLMEMZW3JN"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-DLMEMZW3JN');
    </script>   

    <!-- HTMX -->

    <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.13"></script>

  </head>

  <body>
    <header class="container-fluid">
      <nav class="navbar navbar-expand-lg" aria-label="Main Navigation">
        <section class="container-fluid portada">
          <div class="iconos-derecha col-4">
            <ul class="navbar-nav d-flex align-items-center justify-content-center w-100">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="https://abrealcaldias.org/">< Volver a AbreAlcaldías</a>
              </li>
              <li>
                {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}" class="btn-rueda">
                  Mi Perfil</a> <a class="nav-link" href="{% url 'contenidos:logout' %}">Salir</a>
                {% else %}
                <a class="nav-link" href="{% url 'contenidos:inicio' %}">Inicio</a>
                {% endif %}
              </li>
            </ul>
          </div>
          <div class="container col-4">
            <div class="row">
              <div class="d-flex flex-column justify-content-center align-items-center titulos-portada">
                <p>Construye tu proyecto con</p>
                <a href="{% url 'contenidos:inicio' %}"><h1>DemocraciaKit</h1></a>
              </div>
            </div>
          </div>
          <div class="iconos-izquierda col-4">
            <ul class="navbar-nav d-flex align-items-center justify-content-center w-100">
              <div class="dropdown menuetapas">
                <button class="btn btn-menuheader dropdown-toggle" type="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Etapas
                </button>
                <div class="dropdown-menu menuheader" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item menuheader" href="{% url 'contenidos:etapa1' %}">1 Problemas</a>
                  <a class="dropdown-item menuheader" href="{% url 'contenidos:etapa2' %}">2 Causas</a>
                  <a class="dropdown-item menuheader" href="{% url 'contenidos:etapa3' %}">3 Objetivos</a>
                  <a class="dropdown-item menuheader" href="{% url 'contenidos:etapa4' %}">4 Contexto</a>
                  <a class="dropdown-item menuheader" href="{% url 'contenidos:etapa5' %}">5 Decisión</a>
                  <a class="dropdown-item menuheader" href="{% url 'contenidos:etapa6' %}">6 Empoderar</a>
                  <a class="dropdown-item menuheader" href="{% url 'contenidos:etapa7' %}">7 Evaluar</a>
                </div>
              </div>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contenidos:mikit' %}">Mi Kit</a>
              </li>

            </ul>
          </div>
        </section>
      </nav>
    </header>

    {% block content %}
    {% endblock %}
    <footer class="container-fluid">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-3 col-md-3 col-lg-3 enlaces-rrss">
            <ul class="justify-content-center">
              <li><a href="mailto:info@ciudadaniai.org">¡Queremos conocer tu opinión!</a></li>
            </ul>

          </div>
          <div class="col-12 col-sm-6 col-md-6 col-lg-6 enlaces-rrss">
            <ul class="justify-content-center">
              <li class="logotipo-footer">
                <p><span><b>Democracia</b></span>Kit<b>&lt;</b></p>
              </li>
              <li><a href="https://github.com/ciudadanointeligente" target="_blank"><i class="fa-brands fa-github" aria-hidden="true"></i></a></li>
              <li><a href="https://creativecommons.org/licenses/by/4.0/deed.es" target="_blank"><i class="fa-brands fa-creative-commons" aria-hidden="true"></i></a></li>
            </ul>
          </div>
          <div class="col-12 col-sm-12 col-md-12 col-lg-3 creditos-fci">
            <p>Un proyecto de</p>
            <a href="https://ciudadaniai.org/" target="_blank"><img src="/static/img/logo-fci.svg" alt="logotipo de fundación Ciudadanía Inteligente" class="logo-fci"></a>
          </div>
        </div>
      </div>
    </footer>

    <!-- JavaScript -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var dropdownToggle = document.getElementById('navbarDropdown');
        dropdownToggle.addEventListener('click', function(e) {
          var dropdownMenu = this.nextElementSibling;
          dropdownMenu.classList.toggle('show');
        });
      });
    </script>
  </body>

democraciakit/contenidos/templates/contenidos/pdf1.html
{% load static %}
<!-- Cartilla para descargar -->
<html lang="es">
  <head>
    <title>Cartilla DemocraciaKit</title>
  </head>
  <body onload="window.print()">

    <div class="boxpdf1">
      <img src="{% static 'img/cabecera-card-kit.png' %}" class="cabecerapdf1">
      <div class="cuadropdf1">
        <div class="titulopdf1">
          <h2>Definiciones</h2>
        </div>
        <div class="subtitulopdf1">Estas son las definiciones guardadas de tu problema</div>
        {% if formulario_reciente1 %}
        <div class="formulariorecientepdf1">
          <h4>Quién:</h4>
          <p>{{ formulario_reciente1.uno|linebreaks }}</p>
          <h4>Dónde:</h4>
          <p>{{ formulario_reciente1.dos|linebreaks }}</p>
          <h4>Cuando:</h4>
          <p>{{ formulario_reciente1.tres|linebreaks }}</p>
          <h4>Dolor:</h4>
          <p>{{ formulario_reciente1.cuatro|linebreaks }}</p>
          {% endif %}
        </div>
      </div>
      <img src="{% static 'img/footer-card-kit.png' %}" class="cabecerapdf1">
    </div>
  </body>
</html>

<style>

.boxpdf1 {
  width: 800px;
  max-width: 700px;
  margin: 1%;
}

  .cuadropdf1 {
    padding-left: 2%;
    padding-right: 4%;
    width: 800px;
    max-width: 700px;
  }

  .cabecerapdf1 {
    width: 100%;
  }

  p {
    font-family: 'Nunito', serif;
    font-size: 1em;
    font-weight: 200;
    line-height: 1.3;
    margin-bottom: 0.5em;
  }

  .titulopdf1 {
    font-family: 'Nunito', serif;
    font-size: 1em;
    text-align: center;
    font-weight: 300;
    line-height: 1.6;
    margin-bottom: 0.9em;
  }

  .subtitulopdf1 {
    font-family: 'Nunito', serif;
    font-size: 1.2em;
    text-align: center;
    font-weight: 300;
    line-height: 1.6;
    margin-bottom: 0.9em;
  }

  h2 {
    font-family: 'Nunito', serif;
    font-size: 2.5em;
    font-weight: 300;
    line-height: 0.9em;
    align-items: center;
    margin-bottom: 0.5em;
    margin-top: 0.5em;
  }

  h4 {
    font-family: 'Nunito', serif;
    font-size: 1.5em;
    font-weight: 300;
    line-height: 0.8em;
    margin-bottom: 0.2em;
    margin-top: 0.2em;
  }

  .formulariorecientepdf1 {
    padding-left: 4%;
    padding-right: 4%;
    width: 600px;
    max-width: 600px; 
    display: inline-block;
    word-wrap: break-word;
  }